Repository Charge-Control/Backend, pull requests merged in 2024-05, with the labels that each got.

#6 [feat] 이메일 난수코드 인증 구현
  ChargeControlBackend/build.gradle
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/config/AuthenticationConfig.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/config/MailConfig.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/controller/MemberController.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/domain/EmailVerification.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/domain/Member.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/dto/EmailRequest.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/jwt/JwtFilter.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/jwt/JwtUtil.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/repository/EmailVerificationRepository.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/repository/MemberRepository.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/service/CustomUserDetailsService.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/service/Impl/EmailService.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/service/Impl/MemberServiceImpl.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/service/MemberService.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/config/SecurityConfig.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/exception/EmailAlreadyExistsException.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/exception/EmailNotFoundException.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/exception/InvalidPasswordException.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/exception/MemberException.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/exception/VerificationException.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/response/SuccessStatus.java
Labels: ✨ FEAT ✨, 🐲태근🐲

#9 [fix] 엑세스토큰 재발급 로직 오류 수정 및 토큰 유효시간 변경
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/controller/MemberController.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/domain/Member.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/dto/MemberResponse.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/service/CustomUserDetailsService.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/service/Impl/EmailService.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/service/Impl/MemberServiceImpl.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/config/SecurityConfig.java
Labels: 🐲태근🐲, 🔨 FIX 🔨

#10 [feat] 위반사항 전체, 상세조회 기능 구현
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/controller/MemberController.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/violation/controller/ViolationController.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/violation/domain/Violation.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/violation/domain/violation.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/violation/dto/ViolationResponse.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/violation/repository/ViolationRepository.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/violation/service/ViolationService.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/config/SecurityConfig.java
Labels: ✨ FEAT ✨, 🐲태근🐲

#14 [fix] MainConfig SMTP, CORS, AccessToken 유효시간 변경
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/config/MailConfig.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/service/Impl/MemberServiceImpl.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/config/SecurityConfig.java
Labels: 🐲태근🐲, 🔨 FIX 🔨

#17 [fix] 위반내역 발행날짜 누락 수정
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/violation/controller/ViolationController.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/violation/domain/Violation.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/violation/dto/ViolationResponseDto.java
Labels: 🐲태근🐲, 🔨 FIX 🔨

#18 [feat] 이의신청 조회, CRUD 구현
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/question/controller/QuestionController.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/question/domain/Question.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/question/dto/QuestionRequestDto.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/question/dto/QuestionResponseDto.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/question/repository/QuestionRepository.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/question/service/QuestionService.java
Labels: ✨ FEAT ✨, 🐲태근🐲

#20 [feat] 이의신청 답변 조회, CRUD 구현
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/answer/controller/AnswerController.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/answer/domain/Answer.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/answer/dto/AnswerRequestDto.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/answer/dto/AnswerResponseDto.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/answer/repository/AnswerRepository.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/answer/service/AnswerService.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/question/domain/Question.java
Labels: ✨ FEAT ✨, 🐲태근🐲

#22 [feat] 이의신청 검색 기능 구현
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/question/controller/QuestionController.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/question/repository/QuestionRepository.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/question/service/QuestionService.java
Labels: ✨ FEAT ✨, 🐲태근🐲

#25 [fix] 이의신청 (제목,내용) User 검색 허용 수정
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/question/controller/QuestionController.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/question/service/QuestionService.java
Labels: 🐲태근🐲, 🔨 FIX 🔨

#26 [feat] 충전소 정보 조회 기능 구현
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/chargerlocation/controller/ChargerLocationController.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/chargerlocation/domain/ChargerLocation.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/chargerlocation/dto/ChargerLocationResponseDto.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/chargerlocation/repository/ChargerLocationRepository.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/chargerlocation/service/ChargerLocationService.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/config/SecurityConfig.java
Labels: ✨ FEAT ✨, 🐲태근🐲

#28 [fix] CORS 도메인 수정
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/config/SecurityConfig.java
Labels: 🐲태근🐲, 🔨 FIX 🔨

#30 [fix] CORS 도메인 관리 최적화
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/config/SecurityConfig.java
Labels: 🐲태근🐲, 🔨 FIX 🔨

#33 [fix] 회원정보 핸드폰번호 필드 추가 및 관리자 도메인 변경
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/domain/Member.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/dto/MemberSignUpRequestDto.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/service/Impl/MemberServiceImpl.java
Labels: 🐲태근🐲, 🔨 FIX 🔨

#35 [feat] 주차시 문자 발송 api 구현
  ChargeControlBackend/build.gradle
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/api/member/repository/MemberRepository.java
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/sms/SmsController.java
Labels: ✨ FEAT ✨, 🐰보람🐰

#36 [FIX] 문자발송 API Spring Security 인증 해제
  ChargeControlBackend/src/main/java/com/ChargeControl/www/Backend/common/config/SecurityConfig.java
Labels: 🐲태근🐲, 🔨 FIX 🔨
